<a href="https://colab.research.google.com/github/MarcGaac/DSC1107/blob/main/LabFA_2_DSC1107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
library(tidyverse)
data("starwars", package = "dplyr")

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

**Q1**

In [ ]:
# Structure of the dataset
glimpse(starwars)

# Dimensions
dim(starwars)

# Missing values in selected columns
starwars %>%
  summarise(
    na_height    = sum(is.na(height)),
    na_mass      = sum(is.na(mass)),
    na_homeworld = sum(is.na(homeworld))
  )

Rows: 87
Columns: 14
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Leia Or…
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 2…
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.…
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brown", N…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "light", "light", "…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "blue",…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, …
$ sex        <chr> "male", "none", "none", "male", "female", "male", "female",…
$ gender     <chr> "masculine", "masculine", "masculine", "masculine", "femini…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan", "T…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", "Huma…
$ films      <list> <"A New Hope", "The Empire Strikes Back", "Return of the J…
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>, "Imp…
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced x1",…

[1] 87 14

  na_height na_mass na_homeworld
1 6         28      10

**Q2**

In [ ]:
wide_height <- starwars %>%
  filter(!is.na(species)) %>%                 # non‑missing species
  group_by(species, gender) %>%
  summarise(mean_height = mean(height, na.rm = TRUE), .groups = "drop") %>%
  pivot_wider(
    names_from  = gender,
    values_from = mean_height
  )

wide_height

   species        masculine feminine
1  Aleena          79.0000        NA
2  Besalisk       198.0000        NA
3  Cerean         198.0000        NA
4  Chagrian       196.0000        NA
5  Clawdite             NA  168.0000
6  Droid          140.0000   96.0000
7  Dug            112.0000        NA
8  Ewok            88.0000        NA
9  Geonosian      183.0000        NA
10 Gungan         208.6667        NA
11 Human          182.3913  163.5714
12 Hutt           175.0000        NA
13 Iktotchi       188.0000        NA
14 Kaleesh        216.0000        NA
15 Kaminoan       229.0000  213.0000
16 Kel Dor        188.0000        NA
17 Mirialan             NA  168.0000
18 Mon Calamari   180.0000        NA
19 Muun           191.0000        NA
20 Nautolan       196.0000        NA
21 Neimodian      191.0000        NA
22 Pau'an         206.0000        NA
23 Quermian       264.0000        NA
24 Rodian         173.0000        NA
25 Skakoan        193.0000        NA
26 Sullustan      160.0000        NA
27 Tholothian           NA  184.0000
28 Togruta              NA  178.0000
29 Toong          163.0000        NA
30 Toydarian      137.0000        NA
31 Trandoshan     190.0000        NA
32 Twi'lek        180.0000  178.0000
33 Vulptereen      94.0000        NA
34 Wookiee        231.0000        NA
35 Xexto          122.0000        NA
36 Yoda's species  66.0000        NA
37 Zabrak         173.0000        NA

**Q3**

In [ ]:
long_height <- wide_height %>%
  pivot_longer(
    cols      = -species,
    names_to  = "gender",
    values_to = "mean_height"
  ) %>%
  filter(!is.na(mean_height))   # remove missing mean heights

long_height

   species        gender    mean_height
1  Aleena         masculine  79.0000
2  Besalisk       masculine 198.0000
3  Cerean         masculine 198.0000
4  Chagrian       masculine 196.0000
5  Clawdite       feminine  168.0000
6  Droid          masculine 140.0000
7  Droid          feminine   96.0000
8  Dug            masculine 112.0000
9  Ewok           masculine  88.0000
10 Geonosian      masculine 183.0000
11 Gungan         masculine 208.6667
12 Human          masculine 182.3913
13 Human          feminine  163.5714
14 Hutt           masculine 175.0000
15 Iktotchi       masculine 188.0000
16 Kaleesh        masculine 216.0000
17 Kaminoan       masculine 229.0000
18 Kaminoan       feminine  213.0000
19 Kel Dor        masculine 188.0000
20 Mirialan       feminine  168.0000
21 Mon Calamari   masculine 180.0000
22 Muun           masculine 191.0000
23 Nautolan       masculine 196.0000
24 Neimodian      masculine 191.0000
25 Pau'an         masculine 206.0000
26 Quermian       masculine 264.0000
27 Rodian         masculine 173.0000
28 Skakoan        masculine 193.0000
29 Sullustan      masculine 160.0000
30 Tholothian     feminine  184.0000
31 Togruta        feminine  178.0000
32 Toong          masculine 163.0000
33 Toydarian      masculine 137.0000
34 Trandoshan     masculine 190.0000
35 Twi'lek        masculine 180.0000
36 Twi'lek        feminine  178.0000
37 Vulptereen     masculine  94.0000
38 Wookiee        masculine 231.0000
39 Xexto          masculine 122.0000
40 Yoda's species masculine  66.0000
41 Zabrak         masculine 173.0000

**Q4**

In [ ]:
starwars_extended <- starwars %>%
  mutate(
    bmi = mass / (height / 100)^2,
    height_cat = case_when(
      height < 170            ~ "short",
      height >= 170 & height <= 189 ~ "average",
      height >= 190           ~ "tall",
      TRUE                    ~ NA_character_
    ),
    homeworld = replace_na(homeworld, "Unknown")
  )

glimpse(starwars_extended)

Rows: 87
Columns: 16
$ name       <chr> "Luke Skywalker", "C-3PO", "R2-D2", "Darth Vader", "Leia Or…
$ height     <int> 172, 167, 96, 202, 150, 178, 165, 97, 183, 182, 188, 180, 2…
$ mass       <dbl> 77.0, 75.0, 32.0, 136.0, 49.0, 120.0, 75.0, 32.0, 84.0, 77.…
$ hair_color <chr> "blond", NA, NA, "none", "brown", "brown, grey", "brown", N…
$ skin_color <chr> "fair", "gold", "white, blue", "white", "light", "light", "…
$ eye_color  <chr> "blue", "yellow", "red", "yellow", "brown", "blue", "blue",…
$ birth_year <dbl> 19.0, 112.0, 33.0, 41.9, 19.0, 52.0, 47.0, NA, 24.0, 57.0, …
$ sex        <chr> "male", "none", "none", "male", "female", "male", "female",…
$ gender     <chr> "masculine", "masculine", "masculine", "masculine", "femini…
$ homeworld  <chr> "Tatooine", "Tatooine", "Naboo", "Tatooine", "Alderaan", "T…
$ species    <chr> "Human", "Droid", "Droid", "Human", "Human", "Human", "Huma…
$ films      <list> <"A New Hope", "The Empire Strikes Back", "Return of the J…
$ vehicles   <list> <"Snowspeeder", "Imperial Speeder Bike">, <>, <>, <>, "Imp…
$ starships  <list> <"X-wing", "Imperial shuttle">, <>, <>, "TIE Advanced x1",…
$ bmi        <dbl> 26.02758, 26.89232, 34.72222, 33.33007, 21.77778, 37.87401,…
$ height_cat <chr> "average", "short", "short", "tall", "short", "average", "s…

**Q5**

In [ ]:
film_appearances <- starwars %>%
  select(name, films) %>%
  unnest(films) %>%                    # one row per film appearance
  count(name, sort = TRUE) %>%
  slice_max(n, n = 8)                  # top 8

film_appearances

  name           n
1 R2-D2          7
2 C-3PO          6
3 Obi-Wan Kenobi 6
4 Chewbacca      5
5 Leia Organa    5
6 Luke Skywalker 5
7 Palpatine      5
8 Yoda           5

The column representing films contains a cell for every film title which is stored as a list-column with one or more titles in each cell. We need these films listed in separate rows so that we can use aggregation functions such as count() to sum the number of of times a character appears across films. The result will be a tidy dataset with one observation of a characters appearance in a film per row thus allowing for easier calculation of group-wise summaries.